// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.6.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:ffi' as ffi;

abstract class VelumCore {
  Future<String> helloVelum({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kHelloVelumConstMeta;

  Future<String> getSampleDocument({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetSampleDocumentConstMeta;

  Future<int> multiply({required int a, required int b, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMultiplyConstMeta;
}

class VelumCoreImpl implements VelumCore {
  final VelumCorePlatform _platform;
  factory VelumCoreImpl(ExternalLibrary dylib) =>
      VelumCoreImpl.raw(VelumCorePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory VelumCoreImpl.wasm(FutureOr<WasmModule> module) =>
      VelumCoreImpl(module as ExternalLibrary);
  VelumCoreImpl.raw(this._platform);
  Future<String> helloVelum({dynamic hint}) {
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_hello_velum(port_),
        parseSuccessData: _wire2api_String,
        parseErrorData: null,

        constMeta: kHelloVelumConstMeta,
        argValues: [],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kHelloVelumConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "hello_velum",
        argNames: [],
      );

  Future<String> getSampleDocument({dynamic hint}) {
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_get_sample_document(port_),
        parseSuccessData: _wire2api_String,
        parseErrorData: null,

        constMeta: kGetSampleDocumentConstMeta,
        argValues: [],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kGetSampleDocumentConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_sample_document",
        argNames: [],
      );

  Future<int> multiply({required int a, required int b, dynamic hint}) {
    var arg0 = api2wire_i32(a);
    var arg1 = api2wire_i32(b);
    return _platform.executeNormal(
      FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_multiply(port_, arg0, arg1),
        parseSuccessData: _wire2api_i32,
        parseErrorData: null,

        constMeta: kMultiplyConstMeta,
        argValues: [a, b],
        hint: hint,
      ),
    );
  }

  FlutterRustBridgeTaskConstMeta get kMultiplyConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "multiply",
        argNames: ["a", "b"],
      );

  void dispose() {
    _platform.dispose();
  }
  // Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  int _wire2api_i32(dynamic raw) {
    return raw as int;
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }
}

// Section: api2wire

@protected
int api2wire_i32(int raw) {
  return raw;
}
// Section: finalizer

class VelumCorePlatform extends FlutterRustBridgeBase<VelumCoreWire> {
  VelumCorePlatform(ffi.DynamicLibrary dylib) : super(VelumCoreWire(dylib));

  // Section: api2wire

  // Section: finalizer

  // Section: api_fill_to_wire
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class VelumCoreWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  VelumCoreWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  VelumCoreWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(int ptr) {
    return _get_dart_object(ptr);
  }

  late final _get_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>(
        'get_dart_object',
      );
  late final _get_dart_object = _get_dart_objectPtr
      .asFunction<Object Function(int)>();

  void drop_dart_object(int ptr) {
    return _drop_dart_object(ptr);
  }

  late final _drop_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
        'drop_dart_object',
      );
  late final _drop_dart_object = _drop_dart_objectPtr
      .asFunction<void Function(int)>();

  int new_dart_opaque(Object handle) {
    return _new_dart_opaque(handle);
  }

  late final _new_dart_opaquePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>(
        'new_dart_opaque',
      );
  late final _new_dart_opaque = _new_dart_opaquePtr
      .asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(ffi.Pointer<ffi.Void> obj) {
    return _init_frb_dart_api_dl(obj);
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
        'init_frb_dart_api_dl',
      );
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_hello_velum(int port_) {
    return _wire_hello_velum(port_);
  }

  late final _wire_hello_velumPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'wire_hello_velum',
      );
  late final _wire_hello_velum = _wire_hello_velumPtr
      .asFunction<void Function(int)>();

  void wire_get_sample_document(int port_) {
    return _wire_get_sample_document(port_);
  }

  late final _wire_get_sample_documentPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'wire_get_sample_document',
      );
  late final _wire_get_sample_document = _wire_get_sample_documentPtr
      .asFunction<void Function(int)>();

  void wire_multiply(int port_, int a, int b) {
    return _wire_multiply(port_, a, b);
  }

  late final _wire_multiplyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32, ffi.Int32)>
      >('wire_multiply');
  late final _wire_multiply = _wire_multiplyPtr
      .asFunction<void Function(int, int, int)>();

  void free_WireSyncReturn(WireSyncReturn ptr) {
    return _free_WireSyncReturn(ptr);
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>(
        'free_WireSyncReturn',
      );
  late final _free_WireSyncReturn = _free_WireSyncReturnPtr
      .asFunction<void Function(WireSyncReturn)>();
}

final class _Dart_Handle extends ffi.Opaque {}

typedef DartPostCObjectFnType =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)
      >
    >;
typedef DartPort = ffi.Int64;
